[book]
title = "MMastro.dev's Wiki"
authors = ["MastroDev"]
description = "This is the wiki for my sewlfhosted website, it presents all the documentation for my future reference."
src = "src"
language = "en"
text-direction = "ltr"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[preprocessor.index]
[preprocessor.links]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
no-section-label = false

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
expand = true
heading-split-level = 3

[output.html.fold]
enable = false
level = 0
